import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata = {
   title: "News Portal",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   if (typeof window === "undefined") {
      console.log("🧠 Server render");
   } else {
      console.log("🖥️ Client render");
   }
   return (
      <html lang="en" love-deals="879BC0364EB9EBEE3DBE71B15E175613">
         <body
            className={`${geistSans.variable} ${geistMono.variable}`}
            cz-shortcut-listen="true"
         >
            {children}
         </body>
      </html>
   );
}
